### PR TITLE
Fix build

### PR DESCRIPTION
**Pull request by andrei-ivanov**
Upgrading to parent 21 broke the build for me

### CODE REVIEW

**Comment by andrei-ivanov** [comment]
is this ok to merge?

**Comment by rgoers** [comment]
Andrei, in case you aren't aware the Logging Services projects practice CTR (commit then review). So you don't require our permission to commit. That said, if you want feedback and/or are unsure of a patch by all means create a PR.

**Comment by andrei-ivanov** [comment]
Hmm, I don't see a way to merge it here, maybe I'm missing some permissions?

**Comment by jvz** [comment]
@andrei-ivanov see https://gitbox.apache.org/setup/ to ensure you're configured correctly

**Comment by andrei-ivanov** [comment]
I've just done the setup, but I still don't see a merge button here. Should I have? 🙂

**Comment by rgoers** [comment]
Does GitHub say you are a member?  You can also connect and merge from gitbox but personally I prefer GitHub’s UI.

Ralph

**Comment by andrei-ivanov** [comment]
Ah, it seems that GitHub just needed some time to process the GitBox setup as I've received some mails half an hour later informing me of the repos subscriptions.

Thanks for the help, now I see the proper buttons.

**Pull request merged**
