### PR TITLE
[LOG4J2-2443]

### PR DESCRIPTION
**Pull request by andrei-ivanov**

### CODE REVIEW

**Comment by rgoers** [comment]
This PR has merge conflicts.

**Comment by andrei-ivanov** [comment]
If/when #8 also gets merged, I'll take care of the modifications for this one.

**Comment by andrei-ivanov** [comment]
I should have left this one for later, as it actually depends on the other ones :)

**Comment by andrei-ivanov** [comment]
Conflicts resolved.

⚠Btw, not sure if it matters for semantic versioning, but this PR deletes some classes, the unused exceptions.

**Pull request merged**
